### PR TITLE
player's collisionMask didn't react to spells

### PR DESCRIPTION
**Pull request by AshSimmonds**
RoyalGuard's Orb is a spell, so player.onCollision not firing. Not 100% sure if any other mechanics are affected.

### CODE REVIEW

**Comment by danprince** [comment]
Thanks @AshSimmonds. I think the collisions are working as expected here though, as the spells are responsible for managing the collision with the player, rather than the other way around.

So the problem here is that the `Damaging` behaviour (on the spell) eventually calls the `Die` action, which doesn't end the game properly, because the game over logic is inside the player's `onCollision` callback.

https://github.com/danprince/norman-the-necromancer/blob/1986b980daacbaf64d5101f9ad47f20edd9170cb/src/actions.ts#L19

I think the proper fix would be to move the game over logic into the player's `onDeath` callback, if you're up for tweaking this PR.

```ts
player.onDeath = () => window.location = window.location;
player.onCollision = unit => {
  Damage(player, unit.hp);
  Die(unit);
};
```

I noticed that the `onDeath` method is only called for object's with the `MOBILE` tag at the moment (inside the `Die` action), so you'd also need to pull `object.onDeath()` out of that if statement for this to work.

**Comment by AshSimmonds** [comment]
Ok refactored, see if that's better.

**Comment by danprince** [comment]
@AshSimmonds Let's remove the `if (object.is(PLAYER))` check, then also remember to delete the `object.onDeath` call on L35 of that file.

**Comment by AshSimmonds** [comment]
Yeah cool - was reluctant to enable death for allcomers without a check, in a game about necromancy.

**Comment by danprince** [comment]
Thanks!

**Pull request merged**
